version: '3.8'

services:
  db:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"
    volumes:
      - pg_todo_data:/var/lib/postgresql/data

volumes:
  pg_todo_data: